### ISSUE TITLE
VS Code Welcome page will open each time on load/reload regardless of "open on start" setting

### ISSUE THREAD

**Issue by petecheslock** [getappmap/vscode-appland#1008]
When the AppMap extension is installed on VS Code - extension `v0.127.0`.  The welcome page will open no matter the status of the Appmap tutorial (completed or not) and regardless of the setting "show welcome page on startup" setting.  

Here is a loom of the issue.

https://www.loom.com/share/0749ea5e5a354ee789fc35a1b6aa763c

**Comment by ahabman** [comment]
Confirmed. AppMap extension causes Welcome page to always be shown.

Visual Studio Code
Version: 1.95.2 

AppMap Extension
v0.131.1

Setup:

- Create a new profile (Copy from: none, Source: none)
- Activate new profile
- Restart VS Code, or \>Developer: Reload Window
- Welcome page shown (expected)
- Uncheck "Show welcome page on startup"
- Close Welcome page
- Restart VS Code, or \>Developer: Reload Window
- Welcome page is NOT shown (expected)

settings.json now contains:
```
{
    "workbench.startupEditor": "none"
}
```

extensions.json now contains:
```
[
    {
        "identifier": {
            "id": "appland.appmap",
            "uuid": "41d86b02-68d3-4049-9422-95da6d11cc2e"
        },
        "location": {
            "$mid": 1,
            "fsPath": "/Users/foo/.vscode/extensions/appland.appmap-0.131.1",
            "path": "/Users/foo/.vscode/extensions/appland.appmap-0.131.1",
            "scheme": "file"
        },
        "metadata": {
            "hasPreReleaseVersion": false,
            "id": "41d86b02-68d3-4049-9422-95da6d11cc2e",
            "installedTimestamp": 1731372023367,
            "isPreReleaseVersion": false,
            "pinned": false,
            "publisherDisplayName": "AppMap",
            "publisherId": "f7f1004e-6038-49cd-a096-4e618fe53f77",
            "source": "gallery",
            "targetPlatform": "undefined",
            "updated": false
        },
        "relativeLocation": "appland.appmap-0.131.1",
        "version": "0.131.1"
    }
]
```

To reproduce:
- Install AppMap extension
- Restart VS Code, or \>Developer: Reload Window
- **BUG**: Welcome page is shown. ("Show welcome page on startup" is unchecked)

Again to confirm:
- Uninstall AppMap extension
- Restart VS Code, or \>Developer: Reload Window
- Welcome page is NOT shown (expected)

**Comment by petecheslock** [comment]
This is fixed by https://github.com/getappmap/vscode-appland/pull/1051
