### ISSUE TITLE
When VSCode language model API (copilot more) is enabled, gear icon to change LLM disappears.

### ISSUE THREAD

**Issue by petecheslock** [getappmap/vscode-appland#1034]
AppMap extension version: `v0.129.1`

When you enable the Language Model API integration 

<img width="892" alt="Screenshot 2024-10-07 at 11 15 33 AM" src="https://github.com/user-attachments/assets/9a652e3c-daec-435e-9543-6755cec2293e">

The Gear icon to change the language model disapears until you disable copilot mode in the setting. 

<img width="831" alt="Screenshot 2024-10-07 at 11 20 28 AM" src="https://github.com/user-attachments/assets/25c8b3be-ce23-4e0e-9f4c-176f1720e71a">

**Comment by dustinbyrne** [comment]
This is resolved
