### ISSUE TITLE
You can't drag a file with an octothorpe in the name into the pinned file area of Navie

### ISSUE THREAD

**Issue by petecheslock** [getappmap/vscode-appland#1040]
Appmap extension version `0.130.0`
Using latest VS code.

Recreating the issue:
https://www.loom.com/share/d5b4120c27cc4fc29e0a9e5badafbeb7

If you use a filename like `Python Issue #17` and try to drag + hold shift and drop into navie it will fail.  The error in the console is:

```
EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat '/Users/petecheslock/Desktop/Python Issue '
    at Function.e (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:9061)
    at Object.stat (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:7010)
    at /Users/petecheslock/.vscode/extensions/appland.appmap-0.130.0/src/webviews/chatSearchWebview.ts:75:24
    at async Promise.all (index 0)
    at FH.doPinFiles (/Users/petecheslock/.vscode/extensions/appland.appmap-0.130.0/src/webviews/chatSearchWebview.ts:69:22)
```

Renaming the file to remove the `#` and dropping into Navie will work as expected.

**Comment by apotterri** [comment]
Never heard the term 'octothrope' before. Thanks for sharing. :)

This problem does indeed stem from the `#` in the path. The extension is using `vscode.Uri.parse` to parse the path when it should be using `vscode.Uri.file`: https://github.com/getappmap/vscode-appland/blob/develop/src/webviews/chatSearchWebview.ts#L74 .

A couple of other spots that probably should also be investigated as part of fixing this one
 * https://github.com/getappmap/vscode-appland/blob/develop/src/lib/buildClassMap.ts#L110
 * https://github.com/getappmap/vscode-appland/blob/develop/src/services/findingsIndex.ts#L44
 * https://github.com/getappmap/vscode-appland/blob/develop/src/lib/bestFilePath.ts#L42

There are also some tests that use the anti-pattern `vscode.Uri.parse('file://`. Presumably these test would fail if the URI had special characters in it, but it would better if they used `vscode.Uri.file`, too.

**Comment by petecheslock** [comment]
Lol whoops i misspelled my own joke - its `octothorpe`
