### ISSUE TITLE
Drop the AppMap "pin" feature from VSCode

### ISSUE THREAD

**Issue by brikelly** [getappmap/vscode-appland#430]
Raised by `dave` in the [community Slack](https://appmap-group.slack.com/archives/C03HK5Z9HBK/p1656701419997319).

![Image](https://user-images.githubusercontent.com/573108/176972979-8bdbf494-00e6-468d-824e-7ac84d04da9e.png)

> In VSCode, the AppMap badge interferes with editing:
e.g. I can’t edit the indentation of the text where the AppMap badge is

Tasks:
- [ ] Remove the pin 
- [ ] Remove associated tests for it

**Comment by kgilpin** [comment]
@brikelly OK are these pins causing more trouble than they are worth? This may be causing people to uninstall the extension.

**Comment by brikelly** [comment]
Good point, I don't know for sure, but they are kinda invasive and there's a chance they're causing churn.

**Comment by dustinbyrne** [comment]
I agree, especially if users are reporting it interferes with the text cursor. I've seen this in other extensions and it's a poor experience. I think it's worth dropping.

**Comment by kgilpin** [comment]
The desired action on this story is to drop this feature from VSCode. AppMaps can be opened for any code object with the following command:



![Image](https://github.com/getappmap/vscode-appland/assets/86395/f5e15d77-317a-4bf0-8605-936f8a145066)
![Image](https://github.com/getappmap/vscode-appland/assets/86395/9e4f4760-fd5d-4a24-9521-dcfe42a98083)
