### ISSUE TITLE
Project picker language is more specific when partial are requirements met

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/vscode-appland#431]
![Image](https://user-images.githubusercontent.com/573108/176034303-9ea2f79f-3b7a-4a32-bdc8-81d5ec183279.png)

When test framework is red (but web framework is green):
```
This project meets some of the requirements necessary to continue. Recording of tests is unsupported due to the test framework detected.
```

When web framework is red (but test framework is green):
```
This project meets some of the requirements necessary to continue. HTTP information, SQL information and remote recording capabilities may be disabled due to the web framework detected.
```

**Comment by ahtrotta** [comment]
This is no longer relevant since the new installation flow has shipped
