### ISSUE TITLE
Text is cut off from project picker view

### ISSUE THREAD

**Issue by petecheslock** [getappmap/vscode-appland#476]
AppMap vscode 0.44.0-rc1 release. 
on Mac OS X Montery

The project picker helper bubbles text is cut off when hovering over them.

<img width="965" alt="Screen Shot 2022-10-04 at 11 15 39 AM" src="https://user-images.githubusercontent.com/511733/193858293-40a8d92d-db9c-48f1-b3e3-691459c210cc.png">
<img width="940" alt="Screen Shot 2022-10-04 at 11 15 35 AM" src="https://user-images.githubusercontent.com/511733/193858295-f205d09f-1a4e-480f-ba43-3a54811226ee.png">

**Comment by dustinbyrne** [comment]
There's an `overflow: hidden` in `.header` which appears to have broken this. The rule was meant to prevent the feature labels from overflowing out of the right side of the header when the viewport is narrow.

**Comment by ahtrotta** [comment]
Closed because this was fixed by this commit: https://github.com/getappmap/appmap-js/commit/4bf770a06c106aca4fcac158c9e22c0fafc259f4
