### ISSUE TITLE
Send logs in telemetry messages when scan or index processes fail

### ISSUE THREAD

**Issue by dividedmind** [getappmap/vscode-appland#510]
Sometimes we see telemetry messages of subprocesses failing but we don't have enough information to diagnose it, for example this exception right after enabling analysis:
```
Error: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node --ms-enable-electron-run-as-node /Users/user/Library/Application Support/Code/User/globalStorage/appland.appmap/node_modules/@appland/scanner/built/cli.js scan --watch exited with code 1
at ChildProcess.<anonymous> (/src/services/processWatcher.ts:117:28)
at Object.onceWrapper (node:events:646:26)
at ChildProcess.emit (node:events:538:35)
at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

It's likely the cli has printed some error messages, but we don't see it in `appland.appmap/debug/exception` telemetry event.

**Comment by dustinbyrne** [comment]
I've added a `log` property to `debug/exception` events:
https://github.com/getappmap/vscode-appland/pull/527/commits/2c90a5b37b704e2db9ed9e442bbd3d633f394c04

**Comment by dividedmind** [comment]
> I've added a `log` property to `debug/exception` events: [2c90a5b](https://github.com/getappmap/vscode-appland/commit/2c90a5b37b704e2db9ed9e442bbd3d633f394c04)

Please remember to add this to the telemetry spec :)
Also, note you can use "fixed #issue" in commit messages, too. It would be handy here.
