### ISSUE TITLE
`@appland/appmap/built/cli.js index --watch --appmap-dir` various crashes: SIGKILL, SIGABRT, Status 1, etc

### ISSUE THREAD

**Issue by lachrist** [getappmap/vscode-appland#539]
There is not much information available on telemetry about these failures.

**Comment by lachrist** [comment]
https://portal.azure.com/#view/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fa4af4729-21ee-4e0a-953c-33cc9db5295c%2Fresourcegroups%2Fvscode-extension%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fvscode-extension-analytics/source/AIExtension.SearchV2/query/union%20customEvents%20%7C%20where%20timestamp%20%3E%3D%20datetime(%222022-11-19T14%3A44%3A10.251Z%22)%20and%20timestamp%20%3C%3D%20(datetime(%222022-11-19T14%3A44%3A10.251Z%22))%20and%20session_Id%20%3D%3D%20%224d0e6fdf-558e-4e8c-819a-62dbc42ed2e01668857492613%22%7C%20extend%20logLen%3Dstrlen(customDimensions%5B%22appmap.cli.log%22%5D)%2Clog%3DcustomDimensions%5B%22appmap.cli.log%22%5D%2Cexception%3DcustomDimensions%5B%22appmap.debug.exception%22%5D%7C%20project-reorder%20timestamp%2Cname%2Cuser_Id%2ClogLen%2Clog%2Cexception

**Comment by lachrist** [comment]
Ruled as not a bug.

**Comment by brikelly** [comment]
@lachrist this is marked as In Progress but there's no Assignee. Who is working on it?

**Comment by lachrist** [comment]
I don't know. I don't think I made the change to `in progress`. If it is me, then it is an error. I did not assign anyone, I raised the issue multiple times in standup and on slack though.

**Comment by lachrist** [comment]
Also happening with the `scan` command

https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize?redirect_uri=https%3A%2F%2Fportal.azure.com%2Fsignin%2Findex%2F&response_type=code%20id_token&scope=https%3A%2F%2Fmanagement.core.windows.net%2F%2Fuser_impersonation%20openid%20email%20profile&state=OpenIdConnect.AuthenticationProperties%3D5TaarRaVPdFhlZN-s0W47EBZWnuiLKyr6_NSyiprU1c4BBmAmpAEFUyQgXjqrKkjV3vMA95PgxhyUJaaS4J5lDty8Iv43VvQ0iL-pPaHAEQIB5X6VVgYdlqqANITjoG3j98deJS2piICl2_eFs930T1yH4mAlaQyuyMHj23ragAmSZZwJdbXtydQ2Sr1ZYyod2f4A4Lc4Sm31a6LPj0bDgeBc83K1L9FKaMfPVaGeIPX87YR0zZIIpGSFRbuqowioREDVJwrvJLMbL2kMrJByw4nM5kJQyN6JysI8ZqV5WO9BiyHuvRdLVWtlmlDTSFFdk-Q7_OHMMVY5Jr-1_gWYQYSsAuhaNqcFKBUCQiiDH9cPthUYN9xzebXgzBitotqoqhNMY6rIjIFTnZoZ7-Rjl_qkIXrpLnguUzYf6FAJ0BIqvcxuyz-HfNaRzmMnYjkH1S2E1QX4Dxwrxk6ZE2qHGGZpeHwwJyVsukYRORNLH8&response_mode=form_post&nonce=638052652079374115.NDMxNTU5ZTQtZTc0Mi00NGY3LWI1OWQtOTVhN2ZiNmM5MDFiYzU4NzJjYjktNDc3Yy00MjFkLThhZjMtMTdiZDJhODM0MzI1&client_id=c44b4083-3bb0-49c1-b47d-974e53cbdf3c&site_id=501430&client-request-id=857f1a34-fddb-4c6d-b296-c4088f442b81&x-client-SKU=ID_NET472&x-client-ver=6.22.1.0

**Comment by dustinbyrne** [comment]
`exit code 1` has been broken up into separate issues now that we have additional data:
https://github.com/getappmap/appmap-js/issues/881
https://github.com/getappmap/appmap-js/issues/880

I'm going to close this issue for now
