### ISSUE TITLE
VS Code users are prompted to sign in after they install the extension

### ISSUE THREAD

**Issue by brikelly** [getappmap/vscode-appland#543]

**Comment by Daniel-Warner-X** [comment]
AppMap prompts the user to sign in immediately after they install the extension.

Mockup:

![Image](https://user-images.githubusercontent.com/1229326/205084035-847ed71e-c94e-4710-9dc2-ab62e3e901b9.png)

Loom:

https://www.loom.com/share/fa746f05ed314fc4a7ca3097188ed268

@Daniel-Warner-X todo: create a better list of benefits that a user receives for logging in

@typaulhus todo: implement UI based on Adam's branch that creates the pages: https://github.com/getappmap/appmap-js/pull/877

**Comment by dustinbyrne** [comment]
PR for the VS Code extension is here: https://github.com/getappmap/vscode-appland/pull/549
