### ISSUE TITLE
End-user yarn dependency resolution fails due to `remote archive doesn't match the expected checksum`

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/vscode-appland#547]
E.g.

```
➤ YN0018: │ d3-path@npm:1.0.9: The remote archive doesn't match the expected checksum
➤ YN0018: │ d3-selection@npm:1.4.2: The remote archive doesn't match the expected checksum
➤ YN0018: │ crypto-js@npm:4.1.1: The remote archive doesn't match the expected checksum
➤ YN0018: │ d3-drag@npm:1.2.5: The remote archive doesn't match the expected checksum
➤ YN0018: │ d3-shape@npm:1.3.7: The remote archive doesn't match the expected checksum
➤ YN0018: │ d3-timer@npm:1.0.10: The remote archive doesn't match the expected checksum
➤ YN0018: │ d3-transition@npm:1.3.2: The remote archive doesn't match the expected checksum
➤ YN0018: │ d3-zoom@npm:1.8.3: The remote archive doesn't match the expected checksum
➤ YN0018: │ dashdash@npm:1.14.1: The remote archive doesn't match the expected checksum
➤ YN0018: │ data-urls@npm:2.0.0: The remote archive doesn't match the expected checksum
➤ YN0018: │ debounce-fn@npm:4.0.0: The remote archive doesn't match the expected checksum
➤ YN0018: │ debug@npm:4.3.4: The remote archive doesn't match the expected checksum
➤ YN0018: │ decompress-response@npm:4.2.1: The remote archive doesn't match the expected checksum
➤ YN0018: │ dagre@npm:0.8.5: The remote archive doesn't match the expected checksum
➤ YN0000: └ Completed in 0s 583ms
➤ YN0000: Failed with errors in 3s 118ms
```

**Comment by symwell** [comment]
[Log](https://portal.azure.com/#view/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fa4af4729-21ee-4e0a-953c-33cc9db5295c%2Fresourcegroups%2Fvscode-extension%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fvscode-extension-analytics/source/AIExtension.SearchV2/query/union%20customEvents%20%7C%20where%20timestamp%20%3E%3D%20datetime(%222022-11-30T02%3A29%3A01.171Z%22)%20and%20timestamp%20%3C%3D%20(datetime(%222022-11-30T02%3A29%3A01.171Z%22))%20and%20session_Id%20%3D%3D%20%22b07b991f-6765-4e36-bffa-6c8bf09a76181669775303548%22%7C%20extend%20logLen%3Dstrlen(customDimensions%5B%22appmap.cli.log%22%5D)%2Clog%3DcustomDimensions%5B%22appmap.cli.log%22%5D%2Cexception%3DcustomDimensions%5B%22appmap.debug.exception%22%5D%7C%20project-reorder%20timestamp%2Cname%2Cuser_Id%2ClogLen%2Clog%2Cexception).

dustinbyrne  asks "Do we need `checksumBehavior: reset` here?"

**Comment by symwell** [comment]
Reproduced in a 3rd-party project by running
```
git clone git@gitlab.com:niklaskorz/nkchat.git
cd nkchat
git checkout 6982cd5cfd8481d05f193352ea83621e8fffa2cd
yarn
➤ YN0000: ┌ Validation step
➤ YN0057: │ @nkchat/client: Resolutions field will be ignored
➤ YN0000: └ Completed in 0s
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @nkchat/client@workspace:packages/client doesn't provide jquery@>= 1.11.0 requested by linkifyjs@npm:2.1.9
➤ YN0002: │ apollo-link-ws@npm:1.0.20 [c5863] doesn't provide graphql@^0.11.3 || ^0.12.3 || ^0.13.0 || ^14.0.0 || ^15.0.0 requested by apollo-link@npm:1.2.14
➤ YN0000: └ Completed in 0.31s
➤ YN0000: ┌ Fetch step
➤ YN0018: │ @apollographql/apollo-tools@npm:0.4.7: The remote archive doesn't match the expected checksum
➤ YN0018: │ @babel/core@npm:7.9.0: The remote archive doesn't match the expected checksum
➤ YN0018: │ @babel/core@npm:7.9.0: The remote archive doesn't match the expected checksum
➤ YN0018: │ @babel/core@npm:7.9.0: The remote archive doesn't match the expected checksum
➤ YN0018: │ @babel/helpers@npm:7.9.2: The remote archive doesn't match the expected checksum
➤ YN0018: │ @babel/plugin-transform-block-scoping@npm:7.8.3: The remote archive doesn't match the expected checksum
➤ YN0018: │ @babel/parser@npm:7.9.4: The remote archive doesn't match the expected checksum
➤ YN0018: │ @babel/parser@npm:7.9.4: The remote archive doesn't match the expected checksum
...
➤ YN0018: │ typescript@npm:3.8.3: The remote archive doesn't match the expected checksum
➤ YN0018: │ typescript@patch:typescript@npm%3A3.8.3#builtin<compat/typescript>::version=3.8.3&hash=8cac75: The remote archive doesn't match the expected checksum
➤ YN0018: │ typescript@patch:typescript@npm%3A3.8.3#builtin<compat/typescript>::version=3.8.3&hash=8cac75: The remote archive doesn't match the expected checksum
➤ YN0000: └ Completed in 0.68s
➤ YN0000: Failed with errors in 0.99s
```

**Comment by dividedmind** [comment]
While I'm not against this, I still don't understand why we would need this or what it would fix exactly. If so many checksums don't match as in the original report, obviously there is something weird going on with the network and the archives are coming back corrupted (perhaps a captive proxy is returning an error page instead of them).

Did we see any instance of checksum corruption that doesn't fit this pattern?

**Comment by symwell** [comment]
It could fix yarn calculating an incorrect [mtime](https://github.com/yarnpkg/berry/issues/1142#issuecomment-608428386) to produce/verify .zip archives.  Maybe users running a version of yarn without this [bug fix](https://github.com/yarnpkg/berry/pull/1155) see this error.

It could also be something weird with the network.

**Comment by symwell** [comment]
> Did we see any instance of checksum corruption that doesn't fit this pattern?

I didn't.  I spot checked 10+ instances of this error.  There is some variance in the list of packages but the checksum corruption pattern is the same.

**Comment by symwell** [comment]
I don't see this error in the logs anymore. Closing.
