### ISSUE TITLE
Stacktrace in Finding Summary Page links to the code with line numbers off by one.

### ISSUE THREAD

**Issue by petecheslock** [getappmap/vscode-appland#578]
AppMap VS Code Extension version: v0.58.2
AppMap RubyGem 0.95.0

When viewing the stack trace for a finding in the vscode extension, we'll link to the code base but the line number is off by one. 

For example this stack trace links to 104:
<img width="566" alt="Screen Shot 2022-12-16 at 10 18 25 AM" src="https://user-images.githubusercontent.com/511733/211064418-be359326-f8a3-486a-9b3e-13e5bc2eeb5e.png">

But the actual line number is 105
<img width="555" alt="Screen Shot 2022-12-16 at 10 18 33 AM" src="https://user-images.githubusercontent.com/511733/211064446-8650315f-776a-47c9-80ec-a05ae34e1efd.png">

Relevant AppMap:  [Settings_MigrationsController_GET_show_when_user_is_sign_in_when_user_does_not_have_moved_to_account_renders_show_page.appmap.json.zip](https://github.com/getappmap/vscode-appland/files/10361897/Settings_MigrationsController_GET_show_when_user_is_sign_in_when_user_does_not_have_moved_to_account_renders_show_page.appmap.json.zip)

**Comment by petecheslock** [comment]
@ahtrotta I think you got mentioned on this one last month but we never created an issue to track this.  (sorry I originally @'d you on the wrong Issue)

**Comment by ahtrotta** [comment]
Fixed with #568
