### ISSUE TITLE
Broken Links to external services in AppMap dependency view also not showing as yellow squares

### ISSUE THREAD

**Issue by petecheslock** [getappmap/vscode-appland#579]
AppMap VS Code Extension version: v0.58.2
AppMap RubyGem 0.95.0

External services in an AppMap dependency view should be displayed as a yellow square.  

Additionally when clicking on the external service API you should be taken to the request in the trace view. 

What should happen:
<img width="1394" alt="Screen Shot 2023-01-06 at 12 28 36 PM" src="https://user-images.githubusercontent.com/511733/211065426-6f2e5722-114e-4b38-9da2-09c77d370546.png">

What happens instead.
https://www.loom.com/share/a8f8e5d0661742faac691f2d206d0f42

Relevant AppMap
[1672964806_877527_http_localhost_3000_checkout_update_confirm.appmap.json.zip](https://github.com/getappmap/vscode-appland/files/10361920/1672964806_877527_http_localhost_3000_checkout_update_confirm.appmap.json.zip)

**Comment by dustinbyrne** [comment]
This will be resolved when the findings in AppMap view feature is released.

**Comment by petecheslock** [comment]
Confirmed fixed in `v0.59.0`
