### ISSUE TITLE
VS Code users appear not to be updating

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/vscode-appland#590]
End-user dependencies seem to have a long lag time between updates. This should not be the case. Updates (if available) should be fetched upon initialization.

The install/update process is defined here: https://github.com/getappmap/vscode-appland/blob/master/src/services/nodeProcessService.ts#L129

**Comment by symwell** [comment]
A potential issue is that spawn forks a process that doesn't necessarily complete by the time the call to spawn returns. The `await` in front of spawn is unnecessary, according to vscode (there are three `...`s under await), and perhaps misleading.

![await_spawn](https://user-images.githubusercontent.com/111290954/212170162-947507f5-e9c5-43a9-bb01-59964749fec8.png)

If this is the issue, it means `yarn up` doesn't complete by the time `appmap-win-x64.exe` is executed.
