### ISSUE TITLE
Share when not signed in produces buggy behavior

### ISSUE THREAD

**Issue by brikelly** [getappmap/vscode-appland#596]
To reproduce: 
* Make sure you're not logged in
* Hit Share
* Hit Cancel on the modal confirmation dialog
* Look at the window which we still display: it says a link has been copied (it hasn't), it says "Retrieving link..." (it isn't) and the text "Retrieving link" looks clickable (it isn't).

Loom showing the issue is here: https://www.loom.com/share/614b8b8501374d1191cadeb86a084b12 

MacOS, extension v. 0.62.0

**Comment by kgilpin** [comment]
Share is deprecated. Closing.
