### ISSUE TITLE
Can't open queries or requests

### ISSUE THREAD

**Issue by Trass3r** [getappmap/vscode-appland#616]
Opening an AppMap directly works, both in the Explore view and the sidebar.
But when clicking on an http request or sql query in Explore or the Code Objects view it tries to open a \.appmap.json or \\.appmap.json\ file respectively.
Clicking on one of the unittest methods inside the code tree in Code Objects also doesn't point to the right file. It just tries to append the package + java file path to the workspace.
Maybe it's because the main spring application and thus also the appmap.yml is contained in a subfolder of the workspace?

**Comment by brikelly** [comment]
Hi @Trass3r , thank you for opening this issue. Can you please provide a few details for us to help us move it forward:
* Version of VS Code
* Version of the AppMap VS Code extension which is installed
* Names and versions of frameworks in use (I'm assuming Spring, JUnit)
Thank you!

**Comment by Trass3r** [comment]
Latest versions, vscode 1.75.1, appmap v0.66.0, Windows 10
I just checked spring-petclinic and there it happens too, so SpringBoot 3.0.1, GraalVM JDK 17.

I should also note that opening things works in IntelliJ.

**Comment by petecheslock** [comment]
Hi @Trass3r - Could you try to open the `Developer Tools` in VS Code -
<img width="372" alt="Screen Shot 2023-02-13 at 10 51 16 AM" src="https://user-images.githubusercontent.com/511733/218506123-d1581797-7d19-49e1-9598-31dca5b3763f.png">
 

then open one of the AppMaps with the problem.  If there are any errors in the console can you paste them here?

**Comment by Trass3r** [comment]
Good idea:
```js
 ERR Unable to read file '\.appmap.json' (Error: Unable to resolve nonexistent file '\.appmap.json'): EntryNotFound (FileSystemError): Unable to read file '\.appmap.json' (Error: Unable to resolve nonexistent file '\.appmap.json')
    at Function.c (%LOCALAPPDATA%\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:25871)
    at Object.readFile (%LOCALAPPDATA%\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:24864)
    at AppMapEditorProvider.openCustomDocument (%USERPROFILE%\.vscode\extensions\appland.appmap-0.66.0\src\editor\appmapEditorProvider.ts:91:18)
    at h.$createCustomDocument (%LOCALAPPDATA%\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:167360)
```

**Comment by brikelly** [comment]
Thank you, that's helpful. We will try to reproduce this ourselves now and if we can, we'll get it fixed. Appreciate your patience with this!

**Comment by brikelly** [comment]
Hi @Trass3r , a few more questions to help us reproduce this:

- Are you recording the AppMaps within VS Code or within IntelliJ (using the "menu"-based recording options there)? Or are you recording on the command line?
- Are your AppMap recordings all done from tests, or are you making any "remote" recordings?

I tried opening spring-petclinic maps in VS Code and saw the issue when opening code functions from the Code Objects view. However I was unable to see any errors when opening the HTTP queries or requests, so I'm trying to figure out to reproduce that part of it.

> But when clicking on an http request or sql query in Explore or the Code Objects view it tries to open a .appmap.json or \.appmap.json\ file respectively.

Can you please clarify exactly what you did in that above commend, perhaps with a screenshot of exactly where you clicked?

**Comment by Trass3r** [comment]
Maps were generated via the Maven plugin and one manual remote recording map. Opening any of the maps directly works fine (e.g. `C:\code\spring-petclinic\target\appmap\junit\org_springframework_samples_petclinic_service_ClinicServiceTests_shouldFindVisitsByPetId.appmap.json`).
Then in the Explore AppMaps or Code Objects views it also shows all the different requests and queries. But when clicking on one of those links it fails to open the corresponding file/view/whatever.
