### ISSUE TITLE
High CPU utilization running the VS Code extension

### ISSUE THREAD

**Issue by apotterri** [getappmap/vscode-appland#633]
Every second, the extension scans the entire directory tree under the project root, looking for any files named `appmap.yml`. If the tree is big (e.g. `appmap-js`, with a fully-populated `node_modules`), this will cause very high CPU usage.

**Comment by spaquet** [comment]
Well... looks like it's back with version 0.97.1
I'm experiencing 120 to 140% usage on Apple M1 running OS X. I had to disable AppMap to keep on working on battery.
