### ISSUE TITLE
Sign-in webview is properly rendered

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/vscode-appland#640]
Before fix:

![image](https://user-images.githubusercontent.com/45714532/222201092-af65dad6-d9c5-406e-9de8-b797715984a2.png)

After fix:

![image](https://user-images.githubusercontent.com/45714532/222200779-6e862b40-685f-4130-b3bb-7de8324f2ef7.png)

**Comment by kgilpin** [comment]
What was the problem? The description is empty.
