### ISSUE TITLE
Prompt Python and Java users to install AppMap into mappable project

### ISSUE THREAD

**Issue by Daniel-Warner-X** [getappmap/vscode-appland#698]
When a user opens a mappable Ruby project that does not have AppMap installed they see this:

![Image](https://user-images.githubusercontent.com/1229326/242096398-5c111a4e-a16f-4669-97b7-74ddea1dd123.png)

We want the same behavior for users who have AppMap installed into VS Code and who open a mappable Java or Python project.

[This commit](https://github.com/getappmap/vscode-appland/commit/69f9936b7640c4e6c9bd22615284321324011ada) shows how this was done for Ruby/Rails; we just need similar criteria matching for suitable Java and Python projects. Some useful test projects to clone to test this include:
Java: https://github.com/spring-projects/spring-petclinic
Java: https://github.com/Azure-Samples/tomcat10-jakartaee9
Python: https://github.com/django-oscar/django-oscar
Python: https://github.com/chicagopython/chipy.org
Python: https://github.com/flaskbb/flaskbb
Python: https://github.com/jainamoswal/Flask-Example

When this feature is implemented correctly, a user with the AppMap VS Code extension installed will get a similar message box notification when they first open any of those projects, offering to install AppMap into the project.

**Comment by dividedmind** [comment]
It appears it has been done on purpose in https://github.com/getappmap/vscode-appland/commit/69f9936b7640c4e6c9bd22615284321324011ada — however, the commit message sadly lacks any rationale. @dustinbyrne , do you remember why it was done?

**Comment by dustinbyrne** [comment]
We were originally testing the prompt solely with Rails users to see how it converted.

**Comment by dustinbyrne** [comment]
Should this issue hold off until we've implemented some of the installer QoL fixes?

**Comment by kgilpin** [comment]
I have this already on a branch

**Comment by dividedmind** [comment]
> We were originally testing the prompt solely with Rails users to see how it converted.

Are you sure? The aforementioned commit limits it to Rails — it seems it used to had worked universally before.

**Comment by kgilpin** [comment]
@brikelly @dustinbyrne I feel like we may as well roll this out for Python + Java users now.

**Comment by brikelly** [comment]
Agreed, let's get this one done
