### ISSUE TITLE
Remove deprecated findingEnabled flag

### ISSUE THREAD

**Issue by Daniel-Warner-X** [getappmap/vscode-appland#699]
I'm not sure what conditions produce this CTA but it should never display because AppMap Analysis is on by default for all signed-in users.

![Image](https://user-images.githubusercontent.com/1229326/242334415-6b6654b6-c5eb-4001-a7e1-6debe45da36d.png)

The link to the AppMap Analysis overview is sufficient to display here even when there are no findings yet.

**Comment by dividedmind** [comment]
It seems it's displayed `"when": "appmap.initialized && appmap.userAuthenticated && !appmap.findingsEnabled"`. Are you saying we should remove `findingsEnabled` altogether?
