### ISSUE TITLE
JUnit not detected in `spring-petclinic`

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/vscode-appland#722]
https://github.com/spring-projects/spring-petclinic

![Image](https://github.com/getappmap/vscode-appland/assets/8737782/6cb0fe90-97bb-4a51-a5fa-59658347aeef)

JUnit is pulled in via `spring-boot-starter-test` so it evades detection from project dependency analysis

**Comment by ahtrotta** [comment]
I also cannot reproduce this. I get the exact same output from the analyzer as @dividedmind.

**Comment by dividedmind** [comment]
Closing. Please reopen if you see it again.
