### ISSUE TITLE
JUnit AppMaps not appearing in the AppMap list

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/vscode-appland#730]
AppMaps from the junit test are getting created in `tmp/appmap/junit` but they are not showing up in the IDE extension.

via @petecheslock

![Image](https://user-images.githubusercontent.com/8737782/247756044-d5dad0f9-c4bf-466a-a60b-214450f747cc.png)

![Image](https://user-images.githubusercontent.com/8737782/247756086-099a17be-db90-4832-b822-b83bf95b8812.png)

**Comment by kgilpin** [comment]
Note that because this is a maven project, tmp/appmap is not the right
output directory - according to the conventions used by the Java agent.
