### ISSUE TITLE
The AppMap watcher looks for appmaps according to the `appmap_dir` in the `appmap.yml`

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/vscode-appland#740]
Currently, the appmap watcher in VS Code is hard-coded to look in `tmp/appmap`, `build/appmap`, and `target/appmap`, but if the user specifies another location as their `appmap_dir`, then the AppMaps will not show up in the sidebar.

**Comment by kgilpin** [comment]
Other locations are not allowed. This is not a bug. Please do not implement.
