### ISSUE TITLE
Uninstall instructions are available

### ISSUE THREAD

**Issue by brikelly** [getappmap/vscode-appland#767]
This will link to the doc created in https://github.com/getappmap/applandinc.github.io/issues/1075

**Comment by cyberjunky** [comment]
@brikelly getting rid of appmap completely is a nightmare, extention uninstall from vscode won't cut it at all... the link above is not there anymore. I have looked in all the extension files I could find, but my projects are still complaining about it.
Please give some pointers where to look for appmap extension references..

**Comment by brikelly** [comment]
@cyberjunky uninstall docs are available here: https://appmap.io/docs/reference/uninstalling-appmap.html

Tagging @dustinbyrne @apotterri @kgilpin for visibility.

**Comment by azazar** [comment]
That document doesn't explain, how to properly undo all other modifications to the user account. Such as $HOME/.appmap directory. Such as some process that recreates `appmap.log` even after the extension was uninstalled.

**Comment by petecheslock** [comment]
@azazar Thanks for the report.  We'll work on updating the documents to include this newer folder that AppMap uses for storing things like downloaded CLI binaries, jar files, and local Navie chat history.

**Comment by petecheslock** [comment]
We've shipped the uninstall documentation here: https://appmap.io/docs/reference/uninstalling-appmap.html
