### ISSUE TITLE
AppMap "pins" can be disabled by the user

### ISSUE THREAD

**Issue by brikelly** [getappmap/vscode-appland#769]
### Issue

Given that source code files can be changed after maps are generated, this can lead to the pink "pins" being placed incorrectly within the file viewer.

Therefore we will add an extension setting that allows a user to disable the display of pins if they so choose. It will remain enabled by default when the extension is first installed.

#### Example pin in source code

![Image](https://github.com/getappmap/vscode-appland/assets/45714532/6dfc389f-ef10-4d09-87a1-57ce1f7b5e7d)

#### Where the `AppMap pin enabled` setting should be located

![Image](https://github.com/getappmap/vscode-appland/assets/45714532/cf401557-5911-4e62-b4d3-4cc0c428ab13)

### Details

* Add the setting to the `configuration` field in [`package.json`](https://github.com/getappmap/vscode-appland/blob/develop/package.json#L210).
* [Here](https://github.com/getappmap/vscode-appland/blob/develop/src/decorations/decorationProvider.ts) is where the code for the pin is located.
* Please add a test (either `unit` or `integration`, but please do not add a `system` test).

**Comment by kgilpin** [comment]
@brikelly I'm not sure that this is the best approach. How are users going to know about this option? And then they have to disable the pins for the entire project - not just the files that are out of sync. 

I suggest a different approach that I think is better. We know the timestamp of the AppMaps that include the source file. If the modified date of the source file is later than the timestamp of any of the AppMaps, don't show the Pin.

**Comment by brikelly** [comment]
@kgilpin yeah that's a better approach. Although we should decide if we're going to keep the pins at all first.

**Comment by brikelly** [comment]
Resolved in release 0.101.0
