### ISSUE TITLE
High CPU utilization is back

### ISSUE THREAD

**Issue by spaquet** [getappmap/vscode-appland#771]
Looks like #633 is back.
I'm experiencing high CPU utilization in VSCode of 100 plus % (average around 120%) and rapid battery discharge when the plugin is activated.

Environment:
AppMap 0.97.1
VSCode 1.81.1 for Apple Silicon
OS: OS X

**Comment by brikelly** [comment]
Thank you @spaquet for the report - we will take a look ASAP
