### ISSUE TITLE
Remove OpenAPI from onboarding flow

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/vscode-appland#776]

**Comment by kgilpin** [comment]
WIP branch for this - https://github.com/getappmap/appmap-js/compare/feat/drop-openapi-from-ide-onboarding?expand=1

What I hadn't figured out is what to do about the 5-step "progress pie". Maybe we can keep 5 steps, and step 5 can be "Use the GitHub Action". Shift the Analysis step up by 1. Drop the OpenAPI step.
