### ISSUE TITLE
New users see a notification box when they create their first map

### ISSUE THREAD

**Issue by brikelly** [getappmap/vscode-appland#817]
Similar to how we launch this notification when a user opens a mappable project:
![Image](https://user-images.githubusercontent.com/573108/268423003-1f2067e8-19e9-4365-8c0e-62dd279caeb4.png)

We need to show a similar type of notification message when a user creates their very first map after installing the plugin for the first time, and only show it that one time. The purpose is to help guide new users towards their AppMaps, because they might not notice that they've been created or know how to even open them.

The text of the notification should be:
"You've created your first AppMap! Congratulations."
There should be one button as a primary action, colored in blue as above, with the text "Open your new AppMap"

This notification should only be seen at most once on a user's system.

**Comment by kgilpin** [comment]
I just want to reiterate that we really never need to show a button called “Dismiss” or “No thanks” because the notification box already has a built in “X” in the top right corner.

**Comment by kgilpin** [comment]
For example, the “This project is ready for AppMap” could really just have one button “Open Instructions” and we could alway show this notification only once per project (workspace URL).

**Comment by zermelo-wisen** [comment]
Sure, I'm changing it accordingly.

**Comment by kgilpin** [comment]
Also open the "APPMAPS" tree within the AppMap view / panel
