### ISSUE TITLE
Using the "Delete AppMaps" context menu does not work

### ISSUE THREAD

**Issue by brikelly** [getappmap/vscode-appland#833]
Right click on a map category, and choose the `AppMap View: Delete AppMaps` option. This currently does not work at all, but it should delete the maps in that folder/category.

![Image](https://github.com/getappmap/vscode-appland/assets/573108/8c357092-ce76-43fd-9aef-7f29c4d28466)

It can also be selected at the top level, which would be the same as deleting all maps in the project.

**Comment by kgilpin** [comment]
@dividedmind @dustinbyrne  does this collide with what the indexer is trying to do on AppMap deletion?

**Comment by dividedmind** [comment]
> @dividedmind @dustinbyrne does this collide with what the indexer is trying to do on AppMap deletion?

No, both use `force` so the rm will succeed even when the file already doesn't exist.
