### ISSUE TITLE
High CPU usage by file watchers

### ISSUE THREAD

**Issue by dividedmind** [getappmap/vscode-appland#839]
We create a couple of recursive filesystem watchers causing high CPU usage; with some projects it makes the system almost unusable. VSCode documentation contains suggestions on how to approach filesystem watchers to limit resource use.

**Comment by dividedmind** [comment]
> @dividedmind do you have a link to the VSCode advice you refer to?

https://code.visualstudio.com/api/references/vscode-api#workspace.createFileSystemWatcher says:

> If possible, keep the use of recursive watchers to a minimum because recursive file watching is quite resource intense.

**Comment by dustinbyrne** [comment]
The main issue is `ripgrep` completely chokes on symlink loops. I was noticing the same issue with the [Dev Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) extension. With this PR merged, we're no longer launching a `ripgrep` process on initialization (or if we are, they're not following symlinks).

**Comment by dividedmind** [comment]
> The main issue is `ripgrep` completely chokes on symlink loops when the `--no-follow` flag is present. I was noticing the same issue with the [Dev Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) extension. With this PR merged, we're no longer launching a `ripgrep` process on initialization (or if we are, they're not following symlinks).

Yes :) that was one of the biggest problems. To be clear, we can't tell VSCode to not follow symlinks (as far as I can tell); what we do instead is apply watcher excludes to the search. Watcher excludes usually contain `node_modules` which often seem to be the culprit.
