### ISSUE TITLE
Project Picker classifies Jekyll site as a Node.js project instead of RoR

### ISSUE THREAD

**Issue by Daniel-Warner-X** [getappmap/vscode-appland#911]
The Jekyll repo for appmap.io registers as a Node.js app on the first step of install.

I tried deleting package.json, package lock, yarn lock, app.js, application.js -- it still registers as a node app. 

![image](https://github.com/getappmap/vscode-appland/assets/1229326/b62dd3ec-85e7-426e-bd80-9baa8a280d7e)

**Comment by kgilpin** [comment]
It’s not a RoR app either.
